### PR TITLE
fixing issue #1735 TROE size check for strings before database insert 

### LINKED ISSUE #1735: TROE size check for strings before database insert
Hi,

we have some entities with large string content (escaped json string). Now I found out some truble inserting it to the pg-database. In `/src/lib/orionld/troe/pgAttributeAppend.cpp` there is a buffer size for the insert statement of 2*1024 byte reserved. When we now print the string of the entity to the insert-statement in https://github.com/FIWARE/context.Orion-LD/blob/8a16765cd1be42378d6365e8a79ca4b741204458/src/lib/orionld/troe/pgAttributeAppend.cpp#L223C87-L223C90 there is no check for the length of the string to be printed. So the insert-statement will break. 

The second "problem": In one case an escaped statement was not closed because an `\"` was missing, so that the following char in the SQL statement was escaped and the complete sql statement failed. Maybe in the future there sould be some check against SQL injections?
```
('urn:ngsi-ld:attribute:instance:6113ee80-df0f-11ef-b2b8-0242ac1d0006', 'https://uri.etsi.org/ngsi-ld/default-context/Timestamp', 'Replace', 'urn:ngsi-ld:xxx', '2025-01-30T13:37:36.686+00:00', false, null, 'None', 'String', '2025-01-30T13:37:36.686+00:00', null, null, null, null, null, null, null, null, null, null, '2025-01-30T13:37:41.714Z'),('urn:ngsi-ld:attribute:instance:6113eeda-df0f-11ef-b2b8-0242ac1d0006', 'https://uri.etsi.org/ngsi-ld/default-context/PJson', 'Replace', 'urn:ngsi-ld:RealtimeData:xxx', '2025-01-30T13:37:36.686+00:00', false, null, 'None', 'String', '{\"Id\":\"176017b1-9521-49f9-824a-cd08f43491fd\",\"Name\":\"xxx\",\"xxx\":[{\"xxxx\":[{\"SubProperties\":[{\"SubProperties\":[{\"SubProperties\":[],\"PropertyType\":\"double\",\"Id\":\"9177d75b-7436-45a6-850a-8a79dc47ce0b\",\"Parent\":\"721551b7-70b1-4af3-baef-111c0be73c49\",\"Order\":0,\"PropertyName\":\"xxx\",\"PossibleValues\":null,\"PropertyValue\":\"2\",\"InnerType\":null},{\"SubProperties\":[],\"PropertyType\":\"double\",\"Id\":\"c8cd4b84-0b97-4673-8ebc-5aeabd80334f\",\"Parent\":\"721551b7-70b1-4af3-baef-111c0be73c49\",\"Order\":1,\"PropertyName\":\"xxx\",\"PossibleValues\":null,\"PropertyValue\":\"1\",\"InnerType\":null},{\"SubProperties\":[],\"PropertyType\":\"double\",\"Id\":\"f7279a21-3907-4556-be95-c37a7b289480\",\"Parent\":\"721551b7-70b1-4af3-baef-111c0be73c49\",\"Order\":2,\"PropertyName\":\"xx\",\"PossibleValues\":null,\"PropertyValue\":\"999\",\"InnerType\":null}],\"PropertyType\":\"xxx\",\"Id\":\"721551b7-70b1-4af3-baef-111c0be73c49\",\"Parent\":\"8e6e777a-25fe-40a1-99e5-1b7f60117bb1\",\"Order\":5,\"PropertyName\":\"xxx\",\"PossibleValues\":null,\"PropertyValue\":\"xxx\",\"InnerType\":null},{\"SubProperties\":[{\"SubProperties\":[],\"PropertyType\":\"double\",\"Id\":\"081dc19f-17ab-4cb2-b7ab-dddacdf01bbd\",\"Parent\":\"a3dfeb6e-15e8-4ede-8005-7f6d01f0e812\",\"Order\":2,\"PropertyName\":\"xxx\",\"PossibleValues\":null,\"PropertyValue\":\"xxx\",\"InnerType\":null},{\"SubProperties\":[],\"PropertyType\":\"double\",\"Id\":\"3d4b822e-db62-4893-8507-e34af702a462\",\"Parent\":\"a3dfeb6e-15e8-4ede-8005-7f6d01f0e812\",\"Order\":4,\"PropertyName\":\"xxx\",\"PossibleValues\":null,\"PropertyValue\":\"xxx\",\"InnerType\":null},{\"SubProperties\":[],\"Propert,('urn:ngsi-ld:attribute:instance:6113f07e-df0f-11ef-b2b8-0242ac1d0006', 'https://uri.etsi.org/ngsi-ld/default-context/Source', 'Replace', 'urn:ngsi-ld:xxx:xxx', '2025-01-30T13:37:36.686+00:00', false
```
At position `[],\"Propert,('urn:ngsi-ld:attribute` the SQL string broke.

Greetings,
Carsten

### LINKED ISSUE #1751: possible memory leak using TROE
Hi there,

we are storing a lot of timeseries data using the TROE feature. When running the context broker for longer times, the memory consumption gets higher and highter. So I just did a debug run using valgrind.

If I look at the output there are several places where it complains about possible losses but one realy points out:

```
==1== 13,303,808 bytes in 14 blocks are definitely lost in loss record 2,628 of 2,628
==1==    at 0x4C40B77: realloc (vg_replace_malloc.c:1690)
==1==    by 0x505037: pgAppend(PgAppendBuffer*, char const*, int) (in /usr/bin/orionld)
==1==    by 0x50677C: pgAttributeAppend(PgAppendBuffer*, char const*, char*, char const*, char const*, char*, char*, bool, char*, char*, KjNode*) (in /usr/bin/orionld)
==1==    by 0x506058: pgAttributeBuild(PgAppendBuffer*, char const*, char const*, KjNode*, PgAppendBuffer*) (in /usr/bin/orionld)
==1==    by 0x507001: pgAttributesBuild(PgAppendBuffer*, KjNode*, char*, char const*, PgAppendBuffer*) (in /usr/bin/orionld)
==1==    by 0x50249D: troePostBatchUpsert() (in /usr/bin/orionld)
==1==    by 0x49324B: requestCompleted(void*, MHD_Connection*, void**, MHD_RequestTerminationCode) (in /usr/bin/orionld)
==1==    by 0xBD8F604: connection_reset (connection.c:4349)
==1==    by 0xBD8F604: MHD_connection_handle_idle (connection.c:4832)
==1==    by 0xBD91258: call_handlers (daemon.c:1234)
==1==    by 0xBD96277: MHD_epoll (daemon.c:5149)
==1==    by 0xBD96F14: MHD_polling_thread (daemon.c:5386)
==1==    by 0x7CDA1C9: start_thread (in /usr/lib64/libpthread-2.28.so)
```

When I look at the function troePostBatchUpsert() I saw, that at the beginning of the function the memory for the pointers where to store the INSERT/UPDATE strings is allocated https://github.com/FIWARE/context.Orion-LD/blob/df37d3f50609937e0ba5f7361c6b8bdbec500d4d/src/lib/orionld/troe/troePostBatchUpsert.cpp#L82, then the string is generated but at the end there is no free of the tree buffers
```
  PgAppendBuffer  entities;
  PgAppendBuffer  attributes;
  PgAppendBuffer  subAttributes;
```

Could that be a memory leak?

Greetings
Carsten

### PR DESCRIPTION
**Pull request by cfreyfh**
## Proposed changes

Fixes https://github.com/FIWARE/context.Orion-LD/issues/1735 by:
- Truncating strings before creating the insert statement for postgres.
- Check if buffer for full deserialization of json-property was allocated. If getting null-pointer: output error and ignore property for TROE.

Maybe also fixes https://github.com/FIWARE/context.Orion-LD/issues/1751 but I need to monitor that.

## Types of changes

What types of changes does your code introduce to the project: _Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of
them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before
merging your code._

-   [x] I have read the [CONTRIBUTING](https://github.com/FIWARE/context.Orion-LD/blob/master/CONTRIBUTING.md) doc
-   [ ] I have signed the [CLA](https://fiware.github.io/contribution-requirements/individual-cla.pdf)
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kzangeli** [comment]
Hi,
first of all, thanks for contributing.
Your approach doesn't work though. I'll explain in a comment on the changes, as soon as I have a minute.

File: src/lib/orionld/troe/pgAttributeAppend.cpp [hunk 1]
```diff
@@ -225,8 +225,16 @@ void pgAttributeAppend
   {
     if (valueNodeP->type == KjString)
     {
-      snprintf(buf, bufSize, "%s('%s', '%s', '%s', '%s', %s, %s, %s, '%s', 'String', '%s', null, null, null, null, null, null, null, null, null, null, '%s')",
+      int chars_written = snprintf(buf, bufSize, "%s('%s', '%s', '%s', '%s', %s, %s, %s, '%s', 'String', '%s', null, null, null, null, null, null, null, null, null, null, '%s')",
                comma, instanceId, attributeName, opMode, entityId, observedAt, hasSubProperties, unitCode, datasetId, valueNodeP->value.s, orionldState.requestTimeString);
+      if (chars_written >= bufSize)
```
Comment (kzangeli) [inline src/lib/orionld/troe/pgAttributeAppend.cpp]: So, as I mentioned, this approach won't fix anything.
The problem is 'bufSize', it needs to be precalculated.
I didn't do that when I first implemented this due to being in a hurry to get the TRoE feature out.
It's taken years for the problem to "appear" (it's always been there, obviously.

Let me explain why this approach cannot work:
snprintf returns the number of chars copied into the buffer. We tell the function to not copy more than 'bufSize' bytes.
If the buffer is too small, then only 'bufSize' bytes are copied, and that exact number is returned by snprintf.
I checked the code and bufSize is 2048):
```
  char        localBuf[2 * 1024];
  int         bufSize = sizeof(localBuf);
```

Thus, "chars_written" will be exactly bufSize (2048) (actually 2047 as snprintf is aware of the zero at the end of the string).
We will enter if "if (chars_written >= bufSize)" as chars_written is exatcly bufSize. 2047.
However, the buffer is still too small.
So, it will still not work.
The error has just been changed for another one.

To fix the error, the needed size for the string must be precalculated.

Also, very important, a functional test is needed.
If you had had one, covering the issue, you'd find that it would still fail after this fix.
Functional tests are good (essentail!) for two things:
1. To be used as test case while an issue is being developed/fixed.
2. To run in every sunsequent pull request to assure the fix still works.

No PR is ever merged unless 100% of the functests are working properly.

So, let's start with the functest, that's how I always start fixing an issue.
I assume you have an example entity update that provokes the bug?

File: src/lib/orionld/troe/pgAttributeAppend.cpp [hunk 2]
```diff
@@ -257,6 +265,13 @@ void pgAttributeAppend
       int          renderedValueSize   = kjFastRenderSize(valueNodeP);
       char*        renderedValue       = kaAlloc(&orionldState.kalloc, renderedValueSize);
 
+      // if kaAlloc returns null-pointer, the attribute is to huge -> do not try to write to null-pointer, report error and return
+      if (renderedValue == NULL)
+      {
+        LM_E(("error allocating %d for attribute value", renderedValueSize));
+        return;
+      }
+
```
Comment (kzangeli) [inline src/lib/orionld/troe/pgAttributeAppend.cpp:277]: Now, how do you want to do this?
Inplement it yourself, with my help?
Or do you prefer I do it?

Cheers and thanks for contributing.
It is highly appreciated!

/KZ

**Review by kzangeli — CHANGES_REQUESTED** [review]
Needs a few updates, all explained in comments

File: src/lib/orionld/troe/pgAttributeAppend.cpp (hunk 1 above)
Comment (cfreyfh) [reply src/lib/orionld/troe/pgAttributeAppend.cpp]: Thanks for your comment.
Thats correct, if the buffer is too small for the given string plus the SQL command, we will get into "if (chars_written >= bufSize)". In the if-statement we calculate the maximum length of the given string to fit in the SQL command and write the truncated string with a working query to the database and output a warning.

For example instead of a broken insert command that will block all other inserts for the given entity like
` ('urn:ngsi-ld:attribute:instance:12e00991-88b2-11f0-95a1-79a86b89ca1e', 'https://uri.etsi.org/ngsi-ld/default-context/Text', 'Create', 'urn:ngsi-ld:Test:Test', null, false, null, 'None', 'String', 'anvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvabnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbanvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnavbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvnvbnnvbnvbnnvbnvbn`

We will get a working insert command like
`('urn:ngsi-ld:attribute:instance:12e00991-88b2-11f0-95a1-79a86b89ca1e', 'https://uri.etsi.org/ngsi-ld/default-context/Text', 'Create', 'urn:ngsi-ld:Test:Test', null, false, null, 'None', 'String', 'anvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvabnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbanvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnavbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnv', null, null, null, null, null, null, null, null, null, null, '2025-09-03T10:38:05.044Z')`
but with the string truncated. 

In my opinion this check will be needed nevertheless the buffer is resized. Otherwise we might get a problem with the maximum length of the SQL insert command if someone tries to send entities with large amount of text.

My test-entity is:
```
[
   {
      "id":"urn:ngsi-ld:Test:Test",
      "type":"Test",
      "Text":{
         "type":"Property",
         "value":"anvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvabnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbanvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnavbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbnnvbnvbn"
      }
   }
]
```

File: src/lib/orionld/troe/pgAttributeAppend.cpp (hunk 2 above)
Comment (cfreyfh) [reply src/lib/orionld/troe/pgAttributeAppend.cpp:277]: Well, if it's ok for you, I would like to implement it by myself with your help. Maybe I start with the test-case?

Comment (kzangeli) [reply src/lib/orionld/troe/pgAttributeAppend.cpp:277]: I'd **love** to show you a few things here.
That said, I went ahead and fixed the problem, but, I'd prefer to instead show you how to do it yourself.
If you're interested in learning how to fix issues by yourself (might be valuable for your company) I'd be happy to give you a few hours of training or even many hours.

Comment (cfreyfh) [reply src/lib/orionld/troe/pgAttributeAppend.cpp:277]: Great, so how can we get started?

Comment (kzangeli) [reply src/lib/orionld/troe/pgAttributeAppend.cpp:274]: I'm mostly free all day today.
If you are too, let's meet for an hour or more.
Here's my job email: ken.zangelin@fiware.org  (to set up a meeting).

Also we need a way to "chat".
I'm on discord, whatsapp and google chat. Whichjj one do you prefer?

Comment (kzangeli) [reply src/lib/orionld/troe/pgAttributeAppend.cpp:277]: I'm mostly free all day today.
If you are too, let's meet for an hour or more.
Here's my job email: ken.zangelin@fiware.org  (to set up a meeting).

Also we need a way to "chat".
I'm on discord, whatsapp and google chat. Which one do you prefer?

File: test/functionalTest/cases/0000_ld/troe/troe_put_entity_withLargeString.test [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+HTTP/1.1 201 Created
+Content-Length: 0
+Date: REGEX(.*)
+Location: /ngsi-ld/v1/entities/urn:ngsi-ld:entities:E1
+
+
+
+02. See the string-attribute in the temporal database
+===================================================
+opmode,id,valuetype,entityid,ts
```
Comment (kzangeli) [inline test/functionalTest/cases/0000_ld/troe/troe_put_entity_withLargeString.test]: I'd propose to add the string value here, to make sure the entire string is actually stored in postgres.

Comment (kzangeli) [reply test/functionalTest/cases/0000_ld/troe/troe_put_entity_withLargeString.test]: Fixed in 0063672

**Review by kzangeli — APPROVED** [review]
LGTM (Looks Good To Me)
